<?php

namespace App\Filament\Admin\Resources\UserResource\Pages;

use App\Filament\Admin\Resources\UserResource;
use App\Models\User;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Database\Eloquent\Model;

class EditUser extends EditRecord
{
    protected static string $resource = UserResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\ViewAction::make(),
            Actions\DeleteAction::make(),
        ];
    }

    protected function handleRecordUpdate(Model $record,array $data) : Model{
        $location = $record->location;

//        dd($data);
        if ($location==null){
            $location = $record->location()->firstOrCreate([
                'lat'=>$data['location']['lat'],
                'lng'=>$data['location']['lng'],
                'place_id'=>$data['location']['place_id']

            ])  ;
        }
        $record->location()->first()->update([
            'lat'=>$data['location']['lat'],
            'lng'=>$data['location']['lng'],
            'place_id'=>$data['location']['place_id']

        ]);

//        dd($record->location()->first());
        return parent::handleRecordUpdate($record,$data);

        // TODO: Change the autogenerated stub
    }
}
