<?php

namespace App\Filament\Resources\TaskResource\Pages;

use App\Filament\Resources\TaskResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;

class EditTask extends EditRecord
{
    protected static string $resource = TaskResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }

    protected function mutateFormDataBeforeFill(array $data): array
    {
//        dd($data);
        return parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }
    protected function mutateFormDataBeforeSave(array $data): array
    {
//        dd($data);
        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }

    public function handleRecordUpdate(\Illuminate\Database\Eloquent\Model $record, array $data): \Illuminate\Database\Eloquent\Model
    {
//        dd($data['location']);
        $record->loc()->first()->update($data['location']);

        return parent::handleRecordUpdate($record, $data);
    }

    protected function getRedirectUrl(): ?string
    {
        return ListTasks::getUrl();
    }
}
