<?php

namespace App\Filament\Resources\Settings\PolygonResource\Pages;

use App\Filament\Resources\Settings\PolygonResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class CreatePolygon extends CreateRecord
{
    protected static string $resource = PolygonResource::class;

    protected function handleRecordCreation(array $data): Model
    {
        $data = [
            'data'=>json_encode($data['data']),
            'name'=>$data['name'],
            'place_id'=>Str::uuid()->toString()
        ];
        return parent::handleRecordCreation($data); // TODO: Change the autogenerated stub
    }
}
