<?php

namespace App\Filament\Resources\UserResource\Pages;

use App\Filament\Resources\UserResource;
use App\Models\User;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Database\Eloquent\Model;

class EditUser extends EditRecord
{
    protected static string $resource = UserResource::class;

    protected function getHeaderActions(): array
    {

//        $a = User::count();
        return [
            Actions\DeleteAction::make(),
        ];
    }

    protected function handleRecordUpdate(Model $record,array $data) : Model{
        if (key_exists('place',$data) and key_exists('place_id',$data['place']) ){

            if ($record->location==null){

                $record->location()->create([
                    'place_id'=>$data['place']['place_id'],
                    'lat'=>$data['place']['lat'],
                    'lng'=>$data['place']['lng'],
                ]);
            }else{

            $record->location->update([
            'place_id'=>$data['place']['place_id'],
            'lat'=>$data['place']['lat'],
            'lng'=>$data['place']['lng'],
        ]);
            }
        }
        $record->load('location');
        return parent::handleRecordUpdate($record,$data); // TODO: Change the autogenerated stub
    }



    protected function getRedirectUrl() : ?string{
            return ListUsers::getUrl();
    }
}
